// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-ent-graphql-example/ent/user"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges          UserEdges `json:"edges"`
	user_indicated *int
	selectValues   sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Indication holds the value of the indication edge.
	Indication []*User `json:"indication,omitempty"`
	// Indicated holds the value of the indicated edge.
	Indicated *User `json:"indicated,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
	// totalCount holds the count of the edges above.
	totalCount [2]map[string]int

	namedIndication map[string][]*User
}

// IndicationOrErr returns the Indication value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) IndicationOrErr() ([]*User, error) {
	if e.loadedTypes[0] {
		return e.Indication, nil
	}
	return nil, &NotLoadedError{edge: "indication"}
}

// IndicatedOrErr returns the Indicated value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UserEdges) IndicatedOrErr() (*User, error) {
	if e.loadedTypes[1] {
		if e.Indicated == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.Indicated, nil
	}
	return nil, &NotLoadedError{edge: "indicated"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			values[i] = new(sql.NullInt64)
		case user.FieldName:
			values[i] = new(sql.NullString)
		case user.ForeignKeys[0]: // user_indicated
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (u *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			u.ID = int(value.Int64)
		case user.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				u.Name = value.String
			}
		case user.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_indicated", value)
			} else if value.Valid {
				u.user_indicated = new(int)
				*u.user_indicated = int(value.Int64)
			}
		default:
			u.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (u *User) Value(name string) (ent.Value, error) {
	return u.selectValues.Get(name)
}

// QueryIndication queries the "indication" edge of the User entity.
func (u *User) QueryIndication() *UserQuery {
	return NewUserClient(u.config).QueryIndication(u)
}

// QueryIndicated queries the "indicated" edge of the User entity.
func (u *User) QueryIndicated() *UserQuery {
	return NewUserClient(u.config).QueryIndicated(u)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (u *User) Update() *UserUpdateOne {
	return NewUserClient(u.config).UpdateOne(u)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (u *User) Unwrap() *User {
	_tx, ok := u.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	u.config.driver = _tx.drv
	return u
}

// String implements the fmt.Stringer.
func (u *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", u.ID))
	builder.WriteString("name=")
	builder.WriteString(u.Name)
	builder.WriteByte(')')
	return builder.String()
}

// NamedIndication returns the Indication named value or an error if the edge was not
// loaded in eager-loading with this name.
func (u *User) NamedIndication(name string) ([]*User, error) {
	if u.Edges.namedIndication == nil {
		return nil, &NotLoadedError{edge: name}
	}
	nodes, ok := u.Edges.namedIndication[name]
	if !ok {
		return nil, &NotLoadedError{edge: name}
	}
	return nodes, nil
}

func (u *User) appendNamedIndication(name string, edges ...*User) {
	if u.Edges.namedIndication == nil {
		u.Edges.namedIndication = make(map[string][]*User)
	}
	if len(edges) == 0 {
		u.Edges.namedIndication[name] = []*User{}
	} else {
		u.Edges.namedIndication[name] = append(u.Edges.namedIndication[name], edges...)
	}
}

// Users is a parsable slice of User.
type Users []*User
